categories:
- Phylogenetics
description: Tool for automated alignment trimming
homepage_url: http://trimal.cgenomics.org/trimal
long_description: trimAl is a tool for the automated removal of spurious sequences
  or poorly aligned regions from a multiple sequence alignment.
name: trimal
owner: padge
remote_repository_url: https://github.com/inab/trimal
